### ISSUE TITLE
API doesn't work (Invalid access token)

### ISSUE THREAD

**Issue by huangdengpan** [instructure/canvas-lms#1324] opened 2018-07-20 10:01 UTC
### Summary:
I am trying to get courses through API on my new canvas server, like this:

```https://lms.com/api/v1/courses?access_token=<token>```

But it shows the error:

`{"errors":[{"message":"Invalid access token."}]}`

I am sure the access_token is usable, I get it from my setting page.

### It works on my another canvas server:

```https://lms.famousedu.com/api/v1/courses?access_token=<token>```

So, I am not sure is there any settings need to change?

**Comment by sdb1228** [comment] 2018-07-29 14:18
Hey @huangdengpan Can you give us more information about how you are hitting this url? Are you using postman or trying to access it through the browser?

**Comment by huangdengpan** [comment] 2018-07-29 14:38
Dear Mr. Burnett,

Here is the API address:
http://202.121.178.226:880/api/v1/courses?access_token=nwWgNpGyKZZevEv3uMXvtMDLZejBXpO79yhAjxTqaqD1ldF5Oajqtq6DhZYVe8DM

I’m sure the access_token is correct. If I use Oauth to create an access_token, the access_token is working.

[cid:FF883F0C-C55E-4286-A1D1-7B3B57E4D4BE]

在 2018年7月29日，下午10:18，Steven Burnett <notifications@github.com<mailto:notifications@github.com>> 写道：


Hey @huangdengpan<https://github.com/huangdengpan> Can you give us more information about how you are hitting this url? Are you using postman or trying to access it through the browser?

**Comment by sdb1228** [comment] 2018-07-29 16:55
Hey @huangdengpan is the access token you are using here http://202.121.178.226:880/api/v1/courses?access_token=nwWgNpGyKZZevEv3uMXvtMDLZejBXpO79yhAjxTqaqD1ldF5Oajqtq6DhZYVe8DM created on a users account or created via the oauth? tokens generated through oauth have a pretty short expiration time period (I think by default its 30 minutes? Could be wrong here) You should be able to go to `/profile/settings` and see all your access tokens that are in use to see if it has expired.

**Comment by huangdengpan** [comment] 2018-07-30 01:37
I used a student's account created the access_token by the settings page. There's no time limit for expiration.

![image](https://user-images.githubusercontent.com/16663404/43373230-d7620914-93da-11e8-990e-a9f74f3405b0.png)

**Comment by sdb1228** [comment] 2018-07-30 01:42
Hmmm Dangit! I thought for sure that was it.  I would open up a rails console and look at that access token to ensure its accuracy.  If other access tokens on your account are working and this one isn't the only things I can think of are that its 1. expired or 2. inaccurate.  If you can reproduce this behavior with another access token let me know! For now though I am going to close this out until we have more reproduction steps.

**Closed by sdb1228** 2018-07-30 01:42 UTC

**Comment by huangdengpan** [comment] 2018-07-30 01:52
I already tested the access_token feature on 4 canvas system, the old version before 5 of May is working. But the newer version is not working.
All the access_tokens I get through Oauth is working.
And I am sure the custom access_token is the same as the "Access Token Details" page shows.

**Comment by sdb1228** [comment] 2018-07-30 02:59
Have you tried with any other user? Are all users access tokens broken? I just tried on `release/2018-08-04.07` as well as `release/2018-07-14.24`.  I just checked out a fresh master as well and was unable to reproduce :(.  Is there any other information you can give us about this? Any other reproduction steps?

**Comment by mcfilib** [comment] 2019-02-03 15:01
upgrading to the latest stable branch fixed it for me.

**Comment by schrink** [comment] 2020-05-06 00:37
I have exactly the same issue. All of the keys stopped working all of a sudden. API worked for years normally and I updated to the latest stable few days ago. And it worked well until few hours ago. I haven't changed anything. How is this possible? Do you have any idea what it might be?

**Comment by nhmduc** [comment] 2020-10-07 07:14
> I have exactly the same issue. All of the keys stopped working all of a sudden. API worked for years normally and I updated to the latest stable few days ago. And it worked well until few hours ago. I haven't changed anything. How is this possible? Do you have any idea what it might be?

I have the same issue today ! :(

**Comment by vmiheer** [comment] 2020-11-03 05:04
I got same issue today.

**Comment by ralphotowo** [comment] 2022-01-05 11:21
Was anyone able to fix this? We just upgraded today and same issue.

**Comment by Ardena** [comment] 2022-01-06 02:09
If you look at the token in the rails console, does it show an "expires_at" timestamp in the past?  Currently when I create a token in the UI, it shows "expires at" as blank, but still adds an expires_at into the token on creation.  If you remove the expires_at on the token, it should fix the issue for that token.

If your tokens are showing the expires_at field with a date in them, you probably have a "User-Generated" DeveloperKey with auto_expire_tokens set to true.  This commit prevents that from happening in the future, https://github.com/instructure/canvas-lms/commit/8ac2663d577c8dea7822c320f730354b41de0269, but for anyone seeing the above issue, you'll need to change the field to false.

**Comment by ralphotowo** [comment] 2022-01-06 10:32
Thank you for your response @Ardena. We accessed the console and didn't find an "expires_at" for the token. From the console, everything appears to be fine, however the API still responds with "Invalid access token." Any ideas?
![image_2022_01_06T10_29_25_080Z](https://user-images.githubusercontent.com/1202767/148369309-f4ea7c3a-9ed6-4301-92b9-09d920734429.png)

**Comment by Ardena** [comment] 2022-01-07 01:16
Hmm.  I'm not having that issue right now, though I have a vague recollection of having to recreate an access token a while ago.  What does the associated developer key look like?  Are you only having problems with existing tokens?  Or do new tokens fail too?  What APIs are you using the tokens for?

**Comment by huangdengpan** [comment] 2022-01-07 05:41
check redis-server status
