### ISSUE TITLE
Cached permissions are not invalidated immediately after modification

### ISSUE THREAD

**Issue by va7map** [instructure/canvas-lms#365] opened 2013-11-07 00:49 UTC
Course permissions are cached for up to one hour, even if they are modified. This causes a mismatch between the settings displayed and the actual behavior of the application.

One would expect any modifications to permissions to take effect *immediately*, especially if the UI doesn't indicate otherwise. This issue affects multiple permission settings, not just the `:manage_sections` permission in the example below.

##### Steps to reproduce:

1. Start with the **Manage (create / edit / delete) course sections** permission **enabled**
1. Make sure Redis is properly configured in `config/cache_store.yml`
1. Log in as a non-admin teacher
1. Go to one of the teacher's courses, then **Settings** > **Sections**
1. Check if the teacher can create a new section
1. **Disable** the **Manage (create / edit / delete) course sections** permission
1. Check if the teacher can create a new section

##### Expected results:

The teacher should be able to create a new section in the first time, but not the second.

##### Actual results:

The teacher was able to create a new section both times.

**Comment by simonista** [comment] 2015-12-23 22:37
Hey @va7map, sorry to have never responded to this one.  I can't reproduce this, which hopefully means it's been fixed in the last 2 years. :)  Let me know if you're still having problems with it!

**Closed by simonista** 2015-12-23 22:37 UTC

**Comment by va7map** [comment] 2016-01-05 01:41
@simonista, I was able to reproduce this today in both community and cloud Canvas. Do you see the **Add a New Section** field in step 7?
