### ISSUE TITLE
Admin LTI apps in left navigation should be greyed out

### ISSUE THREAD

**Issue by guillaumemolter** [instructure/canvas-lms#735] opened 2015-12-03 16:20 UTC
As discussed here : https://community.canvaslms.com/thread/7163

[UI convention](https://penncanvas.wordpress.com/2014/11/11/best-practices-hiding-course-navigation-buttons/): course navigation items that are not available to students should be "greyed out".

Bug: When you install an LTI app with the following XML (explicitly only visible to admins) it should appear as greyed out in the menu. 
 
```
            <lticm:options name="course_navigation">  
                <lticm:property name="text">My great app</lticm:property>  
                <lticm:property name="visibility">admins</lticm:property>  
            </lticm:options>
```

Currently it is displayed as a standard "public" item:

![screen shot 2015-12-03 at 11 18 15](https://cloud.githubusercontent.com/assets/1478527/11566254/961ae930-99af-11e5-970c-4390d8d6e8bd.png)

**Comment by klloyd** [comment] 2015-12-03 17:36
This isn't a bug, but is currently working as originally intended (although I agree, it's not inline with the current UI workflow). The suggestion from Rob in the community thread is the appropriate place to submit feature requests for the Canvas product team to consider.

**Comment by rivernate** [comment] 2015-12-03 17:41
Thanks for helping to improve canvas. I'm going to close this since it's not a bug, but please feel free to create a feature request in the community here: https://community.canvaslms.com/community/ideas/feature-ideas

**Closed by rivernate** 2015-12-03 17:41 UTC

**Comment by guillaumemolter** [comment] 2015-12-03 18:02
https://community.canvaslms.com/ideas/4033
