### ISSUE TITLE
Error: The document can not be viewed inline

### ISSUE THREAD

**Issue by checkraiser** [instructure/canvas-lms#244] opened 2012-11-26 01:04 UTC
Hi, i'm migrating a course from canvas.instructure.com to my course on my server, everything is OK,  but there is an error when i view module items as PDF, DOC, the error says: The document can not be viewed inline, you don't have permission to view it. 
I guess this error is from the jquery_preview.js file (or scribd/google docs problem).
Do you know how to fix this issue ?
Thank you very much.

**Comment by claydiffrient** [comment] 2015-01-02 20:15
@checkraiser Is this a problem you are still experiencing? I believe it should be resolved now.  I'm sorry we took so long to respond.  I can't reproduce it.  I'm going to go ahead and close the issue for now.  If it's still indeed a problem please let us know.

**Closed by claydiffrient** 2015-01-02 20:15 UTC
