### ISSUE TITLE
Course Export problem

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#331] opened 2013-07-22 20:17 UTC
Dear Sir/Madam,

I have installed an open source version of Canvas LMS. After I have created the course content export and clicked the download link, I got the Page Not Found error. Could you tell me what might be the problem? Thanks.

Chi-Hou

**Comment by claydiffrient** [comment] 2015-01-02 21:51
@cvong Sorry for the delay responding here.  I just tested this out and I can't reproduce it now.  It likely was already fixed.  I'm going to close the issue, but please let us know if it's still an issue for you.

**Closed by claydiffrient** 2015-01-02 21:51 UTC
