### ISSUE TITLE
What if scores break when given a float

### ISSUE THREAD

**Issue by Nalisarc** [instructure/canvas-lms#1014] opened 2017-03-30 23:52 UTC
### Summary:
In the student view, the what if scores break and give the following error when given a floating-point number.
Uncaught TypeError: (l || "").trim is not a function 
### Steps to reproduce:

 1. As a student go into grades (In any class)
 2. Click an assignment score to enter your own.
 3. Enter a float with that does easily cast into an integer (eg 18.6) 

### Expected behavior:
It should take the entered score, and use that when calculating the grade to show the student. 
### Additional notes:
Rather than putting in the expected score, (18.6, 11.3, 1.1, etc), to be calculated as part of the score.  it instead just leaves the score at its last state.  
For example 86% is shown rather than 85.5%, if 86 was the last state.

**Comment by omarkhan** [comment] 2017-04-03 15:56
Thanks for the report @Nalisarc. I can't reproduce this bug, it works fine for me with decimal numbers:

<img width="871" alt="screen shot 2017-04-03 at 10 46 23" src="https://cloud.githubusercontent.com/assets/793379/24618147/c2f1975c-185b-11e7-9094-a7360e6cdf78.png">

Please try again with the latest master. If you are still having problems, try the [#canvas-lms](http://webchat.freenode.net/?channels=canvas-lms) channel on Freenode or the [mailing list](http://groups.google.com/group/canvas-lms-users).

**Comment by ktgeek** [comment] 2017-04-03 16:18
A fix for this was recently merged to master by the Gradebook team. It was in commit 293678ae8c98c47ae31f403112430dcb4d1e7fc7

**Closed** 2017-04-03 16:26 UTC
