### ISSUE TITLE
Broken icon on homepage

### ISSUE THREAD

**Issue by nerdkid93** [instructure/canvas-lms#675] opened 2015-08-21 13:07 UTC
There is a broken icon on your homepage. It looks like the line `<i class="icon-mini-arrow-down"></i>` is supposed to show a down arrow, but instead the icon shows up like a box. See attached picture...

![capture](https://cloud.githubusercontent.com/assets/6289786/9408852/fee1d168-47e3-11e5-8c1b-d23c1af918b3.PNG)

**Comment by simonista** [comment] 2015-08-21 13:40
Hey @nerdkid93, thanks for the heads up.  Oddly, it seems to be working fine for me: 
<img width="686" alt="screenshot 2015-08-21 07 38 04" src="https://cloud.githubusercontent.com/assets/60822/9409422/b44614ae-47d7-11e5-9b9c-e560b06c59e4.png">

Maybe it's a browser caching issue?  Or trouble downloading our icon font?  Do other icons around the site seem to show up okay?

I'm going to close this since I can't reproduce it, but feel free to re-open with more information if you have it.  Thanks again.

**Closed by simonista** 2015-08-21 13:40 UTC

**Comment by nerdkid93** [comment] 2015-08-21 14:25
It just started working for me as well. Hmm, that was bizare. I did the
normal force refreshing and closing/reopening Chrome. Problem is gone,
though.

Thanks!

---
Christopher Beam
