### ISSUE TITLE
Service 'webpack' failed to build - docker dev setup

### ISSUE THREAD

**Issue by Amaan18** [instructure/canvas-lms#1672] opened 2020-07-17 11:33 UTC
### Summary:
`Service 'webpack' failed to build: Get https://starlord.inscloudgate.net/v2/jenkins/canvas-lms-ruby/manifests/master: no basic auth credentials
`
### Steps to reproduce:
`./script/docker_dev_setup.sh`

### Expected behavior:
Complete dev build
### Actual behavior:
fails to build, says no basic auth credentials.
### Additional notes:
Docker and dory are set up correctly. `dory status` gives the following:
`[*] Nginx proxy:  Running as docker container dory_dinghy_http_proxy
[*] Dnsmasq:  Running as docker container dory_dnsmasq
[*] Resolv:  configured with nameserver 127.0.0.1
`
going to the url in the error message opens a page asking for credentials, then results in 403.

**Comment by sephina** [comment] 2020-07-20 07:33
I've also came across this issue, have you solved it?

**Comment by Amaan18** [comment] 2020-07-21 23:13
> I've also came across this issue, have you solved it?

Not yet, tried elevating permissions, made no difference.

**Comment by sephina** [comment] 2020-07-22 08:14
I've tried the manual setup with ubuntu 16.04 LTS and it worked for me. Probably an issue with docker...

**Comment by taylor-clark** [comment] 2020-07-24 04:39
@sephina any suggestions for getting setup w/ 16.04? I'm running into a couple of different issues unfortunately

**Comment by sephina** [comment] 2020-07-24 05:12
Just go step by step. Make sure you are using node 10.
Where do you have issues?

**Comment by iurev** [comment] 2020-07-24 13:20
The issue is gone after I switched to the `stable` branch (in case if `stable` is OK for you)

But it seems like in the source included docker image which is password protected

**Comment by maths22** [comment] 2020-07-25 13:56
I've brought this issue to the attention of the team responsible for the docker builds, and will follow up once we have a resolution.  It appears this was an inadvertant side effect of a change intended to make our builds more performant that didn't consider the fact that external users wouldn't have access to our internal docker registry.

**Comment by maths22** [comment] 2020-07-28 19:40
This has been fixed in 1bfe6e19b9b3200fd2c62ddcfa278a7e62df3cbb .  Please re-pull master, and let us know if you continue having issues

**Closed by maths22** 2020-07-28 19:40 UTC
