### ISSUE TITLE
Incorrect WAI-ARIA Implementation on Studio Videos Causing Navigation Issues

### ISSUE THREAD

**Issue by dslusser** [instructure/canvas-lms#1504] opened 2019-09-11 19:17 UTC
### Summary:
I believe that Canvas currently has incorrect WAI-ARIA practice on the Studio (previously ARC) Videos that is causing navigation difficulty for all stakeholders in our organization. According to the WAI-ARIA Authoring Practices 8/14/2019 1.1 document, the keyboard focus should be "discernible and predictable" (WAI-ARIA, 2019). The current implementation of the keyboard focus when a Studio video is present on a page causes immediate focus on the play button, regardless of position of the Studio video on the page. The usability pattern causes significant challenges when navigating with a keyboard AND any other traditional means of navigation (mouse, touch, etc.). Upon page load, the focus jumps the entire page to a "random" Studio video present on the page. I use the word "random" because I cannot yet track down the exact pattern of focus when there are multiple Studio videos on one page; it changes based on browser cache refresh and traditional browser refresh/page load.

I am proposing to properly implement the WAI-ARIA discernible and predictable practices when a (or multiple) Studio videos are on a single page. This pattern should mirror the current exact pattern of a page when a Studio video is not present on a page; the first tab index should be the collapse/expand global navigation button.

### Steps to reproduce:

 1. Add some content to a page, then add a Studio video, save the page ("page" is being used for any teacher created content that gets saved and displayed to students).
 2. Immediately notice the jarring jump of focus onto the play button of the Studio video.
 
ALSO:
 1. Add some content to a page, then add multiple Studio videos to the page, save the page.
 2. Immediately notice the "random" jarring jump of focus onto the play button of any one of the Studio videos.

### Expected behavior:

This pattern should mirror the current exact pattern of a page when a Studio video is not present on a page; the first tab index should be the collapse/expand global navigation button; NOT a Studio video (or random Studio video when multiple videos are present).

### Actual behavior:

 1. Add some content to a page, then add a Studio video, save the page (I use the word "page" 
 loosely. "Page" is being used for any teacher created content that gets saved and displayed to students).
 2. Immediately notice the jarring jump of focus onto the play button of the Studio video.
 
ALSO:
 1. Add some content to a page, then add multiple Studio videos to the page, save the page.
 2. Immediately notice the "random" jarring jump of focus onto the play button of any one of the Studio videos.

### Additional notes:

This incorrect behavior extends beyond even the traditional WAI-ARIA context. Teachers, students, parents, instructional designers and all stakeholders are being negatively effected by the jarring and jumping behavior of the Studio video focus. Placing a high priority of this seemingly very small issue is key to our organization (and surely every other organization that utilizes Canvas as their LMS).

https://www.w3.org/TR/wai-aria-practices/#kbd_general_between
https://www.w3.org/TR/wai-aria-practices/#kbd_focus_discernable_predictable

**Comment by dslusser** [comment] 2019-09-17 15:49
Also to make this compliance issue even more of an issue...Try adding Studio videos to multiple quiz questions then take the quiz. The focus and page jump now puts you randomly all over the page. You have no idea where the page and focus will end up or which question will be "selected" because of the focus on the Studio video. Is it question 1? Or maybe it's question 17? How about question 31? It all depends on where your Studio videos are in the quiz and how many videos are added.

**Comment by claydiffrient** [comment] 2019-09-17 16:46
Hi, @dslusser thanks for letting us know about this.  We take accessibility very seriously.  I've passed this along to our Studio team.  It's actually something already ticketed in our internal system. We'll make sure to update this issue when it's been resolved.

**Comment by dslusser** [comment] 2019-09-18 00:20
Awesome, thanks for looking into that @claydiffrient ! I've been fielding a lot of issues related to this one and I'm glad to see it has a ticket. My stakeholders will appreciate the update.

**Comment by benternet** [comment] 2019-09-24 00:07
@dslusser we have deployed a fix. can you confirm that the issue is now resolved?

**Comment by dslusser** [comment] 2019-09-24 00:51
@benternet My initial tests look good and are all passing on latest Chrome, Firefox, and Safari browsers!

**Comment by claydiffrient** [comment] 2019-09-24 01:57
Awesome, sounds like it's taken care of.  I'm going to go ahead and close this out.

**Closed by claydiffrient** 2019-09-24 01:57 UTC
