### ISSUE TITLE
Not able to view recording created by wiziq plugin at canvas lms

### ISSUE THREAD

**Issue by sewakram** [instructure/canvas-lms#696] opened 2015-09-25 05:19 UTC
Hello,
I have deployed the wiziq plugin of canvas lms.It can shedule and launch the class with recording option set but after end the class, recording is not showing at canvas lms.Can any body help me to solve this problem.for more details https://groups.google.com/forum/#!topic/canvas-lms-users/FYBzMdxLzf4
Thanks in advanced!!

**Comment by ccutrer** [comment] 2015-10-08 17:11
@sewakram as this is not a bug with Canvas itself, but with an additional feature you are developing for Canvas, I'm going to close this issue. The mailing list (as you've already linked to) or IRC are likely your best avenues to get help.

**Closed by ccutrer** 2015-10-08 17:11 UTC
