### ISSUE TITLE
Assignments submission time is wrong

### ISSUE THREAD

**Issue by Bicet** [instructure/canvas-lms#1149] opened 2017-10-31 10:03 UTC
### Steps to reproduce:

 1. As a teacher create an assignment with a due date and time
 2. As a student complete the assignment in the hour before the due time

### Expected behavior:
Submitting the document in the hour before the due time, should result in "ON time", but it is set to LATE (see attachment)

### Additional notes:
Server time is ok, timezone is ok, also time of submission is perfect, is only the "late submission" appearing 1 hour before it should appear
<img width="1330" alt="screen shot 2017-10-31 at 11 01 31" src="https://user-images.githubusercontent.com/265162/32218430-1f8a737e-be2b-11e7-8f97-7378fa744240.png">

**Comment by Bicet** [comment] 2017-11-06 10:53
C'mon is it possible that I'm the only one having this problem?

**Comment by omarkhan** [comment] 2017-11-06 22:06
I can't reproduce this. Can you verify that the course is set to the correct timezone? To do this, log in as admin and go to course page -> settings -> time zone.

**Comment by tlimbacher** [comment] 2017-11-09 09:21
I have the very same Problem. If the timezone would be wrong, then a submission should not be possible after "available until.." right? This seems to be the strange thing here--it only affects the submission time and not the availability of the assignment.

**Comment by Bicet** [comment] 2017-11-09 15:42
Yep, it's a real problem also because it happens only on submission. On discussion and announcements the time is reported correctly.

@tlimbacher does it happen to you after the daylight time savings?

**Comment by tlimbacher** [comment] 2017-11-09 16:07
@Bicet can't say if the daylight saving time is the issue. We had no assignments before that. Although I've created the assignments before winter time, the setting of the due dates and the publishing was in winter time.
And yes, the late flag appears only for submissions within due-date - 1h. I still don't get why the submission is flagged with "late" since the due-date and available-until-date are the same. As I understand, they cant be late submissions with this configuration (since no submission should be possible after due-date=available-until-date)

**Comment by omarkhan** [comment] 2017-11-09 18:15
Hi @Bicet - I tried following your steps, but could not reproduce the issue. Could you provide more detailed steps including details of your environment - Canvas version, plugins installed, account, course and user timezones, etc? Thanks!

**Comment by Bicet** [comment] 2017-11-10 08:21
I will try to update to the latest version today or tomorrow, I'm still on july/august version, and let you know.
I've just set the timezone to Europe/Rome in the course, as well the same timezone is set for my teacher and my student test users. The timezone on the server is set on Europe/Rome as well.

The only plugin enabled is turnitin, btw, also if disabled, i've the same problem.

What I've done is to create an assignment, as submission type i put file upload, no other options checked a part for due date with time.

If it can help you to squash this bug I can give you access to canvas and it's server, just drop me a line bicets@gmail.com

**Comment by Bicet** [comment] 2017-11-11 11:25
I’m now synced to github, and it seems everything is back to normal and working

**Comment by spencerolson** [comment] 2018-01-12 18:13
Hi @Bicet, okay for me to close this one out? Sounds like this was fixed.

**Comment by 3arrows** [comment] 2018-02-22 07:49
I think that Canvas has some serious bugs in handling timezone.
The problem of assignments submission time above is caused by using Time.now method in the submission model.

It should be coded with the Time.now.utc, Time.current or Time.zone.xxx, etc. Using Time.now is wrong in Ruby on Rails for the global system application.

If you use Time.now method, it returns the local time of system environment. Datetime settings in config/application.rb will be ignored. This is a specification of the Ruby programing language.
When your Canvas goes live in local timezone (such as CET) other than "UTC" timezone, calculation of time will be wrong in due date of every kind.

So, Instructure should make changes for a number of Time.now method in the whole Canvas application code.

**Comment by 3arrows** [comment] 2018-02-22 08:14
For your reference:

https://docs.ruby-lang.org/en/2.4.0/Time.html
http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html
http://danilenko.org/2012/7/6/rails_timezones/

**Comment by lukfugl** [comment] 2018-02-22 17:48
Thanks for bringing that to our attention, @3arrows.

You are correct that in almost all cases we want to use `Time.zone.now` or `Time.now.utc` and not `Time.now` (the exceptions are rare and only permit optimization, so can be ignored in this discussion). This is something we're aware of as an organization but sometimes old mistakes are unnoticed or new mistakes slip through. :(

I'm assuming that in this case you're talking about the default values for `submitted_at` and `graded_at` in the `infer_values` method, and those do appear to be bugs. I'll pass the info on to the appropriate team.

**Comment by 3arrows** [comment] 2018-03-16 01:47
Thank you for your action, @lukfugl 

In a related move, Using Time.now method in the SummaryMessageConsolidator class causes annoying many notifications depending on the timezone of system environment.

By time of day, a number of messages will not be summarized as a single daily notification.

> lib/summary_message_consolidator.rb

`  def delayed_message_batch_ids
    Shackles.activate(:slave) do
      DelayedMessage.connection.select_all(
        DelayedMessage.select('communication_channel_id').select('root_account_id').distinct.
          where("workflow_state = ? AND send_at <= ?", 'pending', Time.now.to_s(:db)).
          to_sql)
    end
  end`

`  def delayed_message_ids_for_batch(batch)
    DelayedMessage.
      where("workflow_state = ? AND send_at <= ?", 'pending', Time.now.to_s(:db)).
      where(batch). # hash condition will properly handle the case where root_account_id is null
      pluck(:id)
  end`

Please pass this information on to Dev team, too :)

**Comment by Leslie-i80** [comment] 2018-04-24 20:42
Today, Tuesday, April 24, 2008, an assignment folder was open between 8:00 a.m. and 10:45 a.m.  My school is in the Pacific Time zone.  All students submitted their work into this folder at varying times while the folder was open, mainly during the last hour.  Canvas marked all of them late.

**Closed** 2020-05-25 05:33 UTC
Labels: No Activity

**Comment by ralphotowo** [comment] 2021-11-28 12:15
We are currently experiencing this challenge on our self-hosted instance. 
The version being run is of origin/stable/2020-05-09 (Date: Sat May 9 16:55:33 2020)

Can anyone confirm if this issue was resolved in the later versions of Canvas? 
Your response will really help us in determining if we should proceed with an upgrade.
