### ISSUE TITLE
QTI Converter Plugin Issues

### ISSUE THREAD

**Issue by CreepyGnome** [instructure/canvas-lms#1145] opened 2017-10-30 20:53 UTC
Currently, if the QTI Converter Plugin is disabled (which is the default state) I cannot import any QTI packages without getting an error.

Also, if the QTI Converter Plugin is enabled I cannot import a common cartridge that doesn't have QTI without getting an error stating it cannot convert. 

It seems this plugin has no safe state, I cannot leave it on as even Canvas Exported content that you try to import will fail if there are no QTI items and if I leave it off then I cannot import anything that does have QTI items.

I assume this is why the plug-in is disabled by default because of issues like these. Is there any plans to stabilize this plugin so that it can be safely left enabled and not try to convert QTI when there is no QTI and so forth?

**Comment by omarkhan** [comment] 2017-10-30 21:58
Hi @CreepyGnome - thanks for this, let me check with the relevant teams. I'll keep you posted.

**Comment by omarkhan** [comment] 2017-11-01 16:53
@CreepyGnome could you send me a copy of a file your are unable to import when the QTI converter plugin is enabled?

> if the QTI Converter Plugin is enabled I cannot import a common cartridge that doesn't have QTI without getting an error stating it cannot convert

**Comment by omarkhan** [comment] 2017-11-01 16:59
Also - can you confirm you have set up the [QTI migration tool](https://github.com/instructure/QTIMigrationTool/wiki)?

**Comment by CreepyGnome** [comment] 2017-11-01 19:36
I have not done anything special to deal with the QTI migration tool as described in your document. All I did is enable QTI Converter Plugin, and as described it doesn't act as expected when enabled and disabled. As when it is enabled and you don't have QTI a normal CC imscc file will not import and when it is enabled a QTI file does import.

Because when it is enabled QTI stuff seem to import fine therefore I would never assume I needed anything else, least of all something called a Migration Tool as I am not migrating data I am importing new data.

Also I am confused why you don't support QTI out of the box with the default setup seems odd not to.

Your Production Start document (which I have been told is the real document that is correct and not to use the Quick Start doc which is old and bad even though it is still referenced) says:

> The QTIMigrationTool needs to be installed for copying content from one Canvas course to another to succeed. Instructions are at https://github.com/instructure/QTIMigrationTool/wiki. When Canvas is installed activate the plugin in Site Admin -> Plugins -> QTI Converter.

It states that this tool is only when copying content from one CANVAS course to another course. It also states to active the converter plugin.  SO nothing here tells me I need it to IMPORT new QTI course data into an existing course.  The wiki page it references does not clear any of it up either.

You can use any CC and QTI files you want I used the IMS Global example they provide to testing feel free to use those or anything you have laying around as long as the CC doesn't have QTI in it, and the QTI zip is just a full QTI manifest based file and not a CC manfiest based file.

So are you saying I have to do all that QTIMigrationTool stuff to make the Plugin work as I would expect and not block CC imports while allowing also QTI imports?

I am more confused than before please tell me how to make **pure** Common Cartridge and QTI imports (not migrations) work without having to toggle back and forth between enabling and disabling a Canvas Plugin?

**Comment by omarkhan** [comment] 2017-11-01 21:17
I have spoken to someone more familiar with these things, who has confirmed that the QTI migration tool is a hard dependency for the QTI converter plugin. I agree that the docs here could be improved. I would suggest trying again after installing the QTI migration tool. If you can contribute improvements to the documentation it would be greatly appreciated! Thanks.

**Comment by CreepyGnome** [comment] 2017-11-01 23:17
I will see if we can give it a try within the next week or so. We have tried to lock down our Canvas installs so may take some time to get one changed to test on.  I will update once tested. Thanks.

**Comment by simonista** [comment] 2017-11-08 22:36
Going to close this for now, since the issue is almost certainly missing https://github.com/instructure/QTIMigrationTool.  Please feel free to reopen if that doesn't clear it up.

**Closed by simonista** 2017-11-08 22:36 UTC

**Comment by CreepyGnome** [comment] 2017-11-08 22:41
Yeah sorry, adding the migration tool fixed the issue and we don't have to enable the QTI Converter Plugin at all. The migration tool is just picked up automatically. 

I would suggest this isn't closed until at least the documentatuon is updated to make it clear this is not just for migration and that this is required for all QTI support.

With that said I would recommend making the migration tool part of official product and merged in so that it is there by default and QTI just works always without administrator interaction.

**Comment by CreepyGnome** [comment] 2017-11-08 22:45
@simonista BTW What is the purpose of that QTI Converter Plugin? Since it doesn't have to be enabled with the migration tool and it doesn't work right when it is enabled without the migration tool. Seems like another level of confusion as there is a plug-in visible in the UI.

**Comment by simonista** [comment] 2017-11-08 22:52
If I'm reading https://github.com/instructure/canvas-lms/blob/stable/gems/plugins/qti_exporter/lib/qti_exporter/engine.rb#L34 correctly, it looks like it is auto-enabled if it can detect the QTIMigrationTool, but that can be overridden.  I'm not sure beyond that, I'm not super familiar with this code.

I've tried to clarify the wording on https://github.com/instructure/canvas-lms/wiki/Production-Start#qtimigrationtool a bit.

**Comment by CreepyGnome** [comment] 2017-11-08 23:00
@simonista I just checked and yes we had it disabled before installing the migration tool and it is currently enabled without our interaction.

So that is a horrible user experience, as this plugin does do what I thought it did but enabling it doesn't actually work. I have to jump down to the CLI and run some commands to get some files into a location that didn't exist. Once that is done this plugin will automatically enable itself.

Seems like a plugin that requires something to be installed under the covers should not be visible/available until it is in a state that it can work. Where I would say that the migration tool should be there by default and the plugin enabled by default and it can then be disabled the site admin if needed.

**Comment by CreepyGnome** [comment] 2017-11-08 23:04
@simonista alternatively if you leave the plugin but change that when they click on it instead of allowing it to be enabled and it not working right that it would behind the scenes just install migration tool after being given permission to do so. THen it can enable itself, that would be a good user experience with it disabled by default.  However not sure why QTI would be disabled by default or even optional personally.
