### ISSUE TITLE
Bug on changing setting options

### ISSUE THREAD

**Issue by huangdengpan** [instructure/canvas-lms#1262] opened 2018-03-26 17:53 UTC
First, thank you for giving us so great system.

Here is a bug on the setting page(I reinstall canvas for 3 times, so I believe it is a bug):

Canvas Version: 20180327(The time I downloaded), canvas-lms-master.zip

When I open the feature of "Use remote service for notifications"
![image](https://user-images.githubusercontent.com/16663404/37923105-f09e1de6-3160-11e8-8264-2fc30d9da488.png)

Then refresh the page, it shows the error page to me:
![image](https://user-images.githubusercontent.com/16663404/37922829-42656144-3160-11e8-9ec9-4c94ce3bf9e6.png)

And I do not know how to fix it o(╯□╰)o.

Last, best wishes for all the people who works on Canvas !

**Comment by huangdengpan** [comment] 2018-03-26 18:06
![image](https://user-images.githubusercontent.com/16663404/37924066-5a561d2c-3163-11e8-90ad-cf06f2e9e192.png)

**Comment by huangdengpan** [comment] 2018-03-26 18:09
@sdb1228 
I tried it again, I changed the option about "Use remote service for notifications", it works well.
after I change the other options and refresh, the error comes again.
It's weird.

**Comment by sdb1228** [comment] 2018-03-26 18:15
@huangdengpan I am sorry that we didn't handle that error better but it looks like you need to set up your signing secret.

**Comment by huangdengpan** [comment] 2018-03-26 18:17
@sdb1228 
Could you please let me know which file should I change?

**Comment by mdjasper** [comment] 2018-03-26 18:18
I think this is a duplicate of https://github.com/instructure/canvas-lms/issues/1076

and a solution is given here https://github.com/instructure/canvas-lms/issues/1076#issuecomment-316030823

**Closed** 2018-03-26 18:27 UTC

**Comment by huangdengpan** [comment] 2018-03-26 18:30
@sdb1228 @mdjasper 
Thank you very much !
