### ISSUE TITLE
Problem with the calendar: back/forward arrows only work for one month AND it sometime jumps one month

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#362] opened 2013-10-31 16:06 UTC
We can find the following issue in this error report: https://github.com/instructure/canvas-lms/issues/170 

**In the main calendar view, the back and forward arrows will work for only one month. After that they stop working at all: from September you can navigate to October, but from that you can't go back to September of go further to November. The calendar at the sidebar works like a charm.
Shall I open a new issue for this?**

As I also encounter the problem, I open a new issue. 

Also, I have found another issue: when the date is the 31th (not sure about that, may be true whatever the date), the "next" arrow seems to jump one month. Today (October 31th), for instance, it jumps to December (skipping November).

Do you have any clue on how to solve that? 
Thanks!

**Comment by claydiffrient** [comment] 2015-01-14 16:32
@Kulgar Sorry that we haven't responded sooner to this.  I can't reproduce the problem now, so I'm assuming it's been fixed.  I'm going to close the issue, but feel free to reopen it if it's still a problem for you.

**Closed by claydiffrient** 2015-01-14 16:32 UTC
