### ISSUE TITLE
docker-compose build not work (rake canvas:compile_assets)

### ISSUE THREAD

**Issue by fadeev2010** [instructure/canvas-lms#1051] opened 2017-06-06 08:46 UTC
### Summary:
Docker version 1.12.0, build 8eab29e
docker-compose version 1.13.0, build 1719ceb

### Steps to reproduce:

 1. I use branch stable
 2. docker-compose build

### ERROR:

Step 26 : RUN bundle exec rake canvas:compile_assets
 ---> Running in 9541879bf9af
/home/docker/.gem/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/home/docker/.gem/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
--> Starting: 'Making sure node_modules are up to date'
node is: v6.10.3 (/usr/bin/node)
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
--> Finished: 'Making sure node_modules are up to date' in 8.93615941600001
--> Starting: 'compile css (including custom brands)'
fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/src/app/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (/usr/src/app/node_modules/node-sass/lib/extensions.js:123:13)
    at foundBinariesList (/usr/src/app/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/src/app/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/src/app/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/src/app/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/src/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/brandable_css/lib/compileBundle.js:7:39)
rake aborted!
Error running BrandableCSS CLI: ./node_modules/.bin/brandable_css
/usr/src/app/lib/brandable_css.rb:294:in `block in run_cli!'
/usr/src/app/lib/brandable_css.rb:277:in `run_cli!'
/usr/src/app/lib/brandable_css.rb:257:in `compile_all!'
/usr/src/app/lib/tasks/css.rake:12:in `block (3 levels) in <top (required)>'
/usr/src/app/lib/tasks/css.rake:12:in `block (2 levels) in <top (required)>'
/usr/src/app/lib/tasks/canvas.rake:62:in `block (2 levels) in <top (required)>'
/home/docker/.gem/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => css:compile
(See full trace by running task with --trace)
ERROR: Service 'webpack' failed to build: The command '/bin/sh -c bundle exec rake canvas:compile_assets' returned a non-zero code: 1

**Comment by tierra** [comment] 2017-06-08 02:37
This is something that broke on the master branch not too long ago, and is just now hitting the stable branch, but it's fixed in the master branch, and I would suggest moving to that branch for docker development.

**Comment by lvalladares** [comment] 2017-06-08 15:22
@tierra solved for me with this, but after starting the compose i've to enter in the canvas web container and execute this to see the styles: 

`./node_modules/brandable_css/bin/brandable_css `

when this will be pushed to stable? thanks

**Comment by tierra** [comment] 2017-06-09 02:48
The fix should hit the stable branch on the 24th. It could come sooner, but it's not a bug that affects our production environments, so it's unlikely be hotfixed to stable.

**Comment by thelastinuit** [comment] 2017-08-22 15:29
For me, it just get stuck
`WARN: Side effects in initialization of unused variable dataLength [0:112274,10]`
while compiling assets...

does anyone have this issue?

**Comment by frob** [comment] 2018-07-02 17:15
Did this fix ever hit stable? 

> but it's not a bug that affects our production environments, so it's unlikely be hotfixed to stable.

@tierra it is kind of a bad attitude for an open source project. It is pretty close to saying "How is that my problem!" when stable is broken.

I bring this up because, I am on stable and I am going through the steps to bring up a docker based development environment and it is failing in a similar way. Is this just the mentality of the people running the project?

**Comment by tierra** [comment] 2018-07-02 17:43
> Did this fix ever hit stable?

It hit stable branch a year ago. Chances are pretty good that your issue isn't the same problem. Perhaps you should open a new issue with details about the errors you're seeing?

**Comment by frob** [comment] 2018-07-03 05:50
Thank you for the quick response to this comment. I apologize if my comment came off as negative. I understand how open source works, and for the most part I would say you are doing open source correctly. However, after following the documentation on setting up an environment with docker on both the "stable" branch and the most current released tag, then finding a year old open comment where a member says the fix is unlikely to be rolled into stage you can understand that it is a little disappointing.

Maybe, if this issue is stale it should be closed. I will post a follow up issue if need be.

**Closed** 2020-08-02 03:52 UTC
Labels: No Activity
