### ISSUE TITLE
Canvas loads image over http even when loaded over https

### ISSUE THREAD

**Issue by juniorb2ss** [instructure/canvas-lms#1286] opened 2018-04-27 14:04 UTC
### Summary:

While using canvas (loaded over https), and after logging in, a certain image (/images/messages/avatar-50.png) is loaded over http, and viewing the source of the generated html page confirms that the image url uses http.

Using:
1 - S3
2 - CDN (CloudFront)

### Steps to reproduce:

 1. SSL Proxy With CloudFront
 2. If access canvas with https URL some assets and API url is generated with http

### Expected behavior:

All page resources are loaded via https, and browsers show the appropriate icon indicating that all resources were loaded securely.

### Additional notes:

Compiled from source with ssl: true is specified in domain.yml under production.

Same problem: #1093 but not has solution.

**Comment by tierra** [comment] 2018-04-27 23:31
Welcome @juniorb2ss, we use github issues for bugs only, for support please see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help). Looks like you found the IRC channel just fine, and we're happy to continue helping there as much as we can. This looks like a setup/configuration issue though, and not a bug, so I'm going to close this out until it's confirmed to be an actual bug.

**Closed by tierra** 2018-04-27 23:31 UTC

**Comment by juniorb2ss** [comment] 2018-04-28 21:10
@tierra 

Thanks for reply.

It really was not a problem in the code, although we could improve that.

The problem was regarding the X-Forwarded-Proto header, I'm using cloudfront for ssl proxy. By default the cloudfront removes `X-Forwarded-Proto` and switches to `Cloudfront-Forwarded-Proto`. As the environment is checked internally in the code through this header, if it does not exist the environment is always returned `http` schema, which is what happened.

We can think of something to improve this.

I know it is a responsibility of http reverse proxy, but in the internal library enable possibility to pass the correct header photo.
