### ISSUE TITLE
Terms of Service Agreement error

### ISSUE THREAD

**Issue by fmarkwong** [instructure/canvas-lms#654] opened 2015-07-02 23:03 UTC
After doing a Quick Start installation (on OS X 10.10.3) when I log in and submit the Terms of Agreement, instead of going to the dashboard, it redirects me to an API url and shows this in the browser:

`while(1);{"id":1,"name":"email","sortable_name":"email","short_name":"email","login_id":"email","locale":null,"permissions":{"can_update_name":true,"can_update_avatar":false}}`

Others have experienced the same issue:  https://groups.google.com/forum/#!topic/canvas-lms-users/HydNUZsCrAw

**Comment by claydiffrient** [comment] 2015-07-03 01:10
@fmarkwong Thanks for reporting this error.  I have been working hard to find the cause of the error.  Can you double check that all your assets have compiled properly without error with `bundle exec rake canvas:compile_assets` ?

In the meantime though to get you up and running, you can run `Setting.set('terms_required', 'false')` from your rails console and that should get you through it for the time being.

**Comment by fmarkwong** [comment] 2015-07-06 03:09
@claydiffrient I compiled assets successfully without errors.  I did get some Jammit warnings:
```
--> Starting: 'Jammit'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/bundles/facebook.css'
--> Finished: 'Jammit' in 0.70261
--> Finished: 'Compile sass and make jammit css bundles' in 39.628053
```

Thanks for the Setting tip.  It worked and I'm on my way for now!

**Comment by b0rgbart3** [comment] 2015-07-19 18:25
Hi Clay - 
I think you're right to ask about whether or not the assets have compiled correctly - because I had to use this workaround for this bug too. -- and I was NOT able to compile assets correctly.

Here are the error messages:

module.js:338/controllers/lti_api_controller.rb.
    throw err;
          ^
Error: Cannot find module 'compute-cluster'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/bartdority/Documents/DesignWork/ClientWork2015/Clients/AxisMundi/CODE/repos/Canvas/canvas3/script/compile-sass.js:1:86)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "compile-sass"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! canvas-lms@0.0.0 compile-sass: `node script/compile-sass.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas-lms@0.0.0 compile-sass script 'node script/compile-sass.js'.
npm ERR! This is most likely a problem with the canvas-lms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/compile-sass.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas-lms
npm ERR! There is likely additional logging output above.
⌌ Parsing app/controllers/lti_api_controller.rb...
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bartdority/Documents/DesignWork/ClientWork2015/Clients/AxisMundi/CODE/repos/Canvas/canvas3/npm-debug.log
npm WARN package.json canvas_quizzes@1.0.0 No repository field.
npm WARN package.json canvas_quizzes@1.0.0 No license field.
[error]: Unhandled exception in YARD::Handlers::Ruby::ModuleHandler:
[error]:   in `app/controllers/filters/live_assessments.rb`:19:

	19: module Filters::LiveAssessments

**Comment by simonista** [comment] 2015-07-29 21:17
Fixed in the above commit, should be on the stable branch on 8/8

**Closed by simonista** 2015-07-29 21:17 UTC
Labels: Confirmed
