### ISSUE TITLE
Imprort Common Cartridge with LTI Links leads to unusable LTI links in some cases

### ISSUE THREAD

**Issue by mradcliffe** [instructure/canvas-lms#297] opened 2013-04-30 15:45 UTC
I am not familiar with Canvas LMS in-depth, but as I tried to learn the basics in order to integrate LTI links via common cartridge I ran into a couple of user experience issues.

### Steps to reproduce
1. Import Common Cartridge with LTI link resource.
2. Add LTI link as modulue via content import process.
3. Go to Course Settings and configure the OAuth consumer information for the LTI link.
4. Go to Modules and try the LTI link. The LTI link will still use the "dummy" OAuth consumer.
5. Add External Tool Content to another module.
6. Try newly added External Tool Content and OAuth consumer information is used.

I do not think  that this is proper behavior. There should never be a case where a LTI link is passing fake OAuth information. I am not sure of the resolution for Canvas LMS in this case. Either importing into modules for LTI links should be disallowed, or content instances should be updated with the OAuth consumer information after it is configured by the user.

**Comment by claydiffrient** [comment] 2015-01-06 00:02
@mradcliffe Is this still happening for you?  I'm told that it is potentially fixed now.

**Comment by mradcliffe** [comment] 2015-01-06 14:42
Hi clay, I'm not sure if I'll be able to confirm this in the near future at the moment.

I think this can be confirmed independently if after importing a Common Cartridge with LTI link resource. Here's an example manifest and resource that can be zipped (on OS X) if located in the same directory: `zip -r -X ~/Desktop/lti-test.imscc .`

000001/BasicLTI.xml 
```xml
<?xml version="1.0"?>
<cartridge_basiclti_link xmlns="http://www.imsglobal.org/xsd/imslticc_v1p0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:blti="http://www.imsglobal.org/xsd/imsbasiclti_v1p0" xmlns:lticm="http://www.imsglobal.org/xsd/imslticm_v1p0" xmlns:lticp="http://www.imsglobal.org/xsd/imslticp_v1p0" xsi:schemaLocation="http://www.imsglobal.org/xsd/imslticc_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticc_v1p0.xsd http://www.imsglobal.org/xsd/imsbasiclti_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imsbasiclti_v1p0p1.xsd http://www.imsglobal.org/xsd/imslticm_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticm_v1p0.xsd http://www.imsglobal.org/xsd/imslticp_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticp_v1p0.xsd">
    <blti:title>Online Resource</blti:title>
    <blti:custom>
        <lticm:property name="destination">resource/1210</lticm:property>
    </blti:custom>
    <blti:launch_url>http://example.com/lti</blti:launch_url>
    <blti:secure_launch_url>https://example.com/lti</blti:secure_launch_url>
    <blti:vendor>
        <lticp:code>example.com</lticp:code>
        <lticp:name>Example Company</lticp:name>
        <lticp:contact>
            <lticp:email>admin@example.com</lticp:email>
        </lticp:contact>
    </blti:vendor>
</cartridge_basiclti_link>
```
imsmanifest.xml
```xml
<?xml version="1.0"?>
<manifest xmlns="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:lomimscc="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest" xsi:schemaLocation="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1 http://www.imsglobal.org/profile/cc/ccv1p1/ccv1p1_imscp_v1p2_v1p0.xsd http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest http://www.imsglobal.org/profile/cc/ccv1p1/LOM/ccv1p1_lommanifest_v1p0.xsd" identifier="stuff">
    <metadata>
        <schema>IMS Common Cartridge</schema>
        <schemaversion>1.1.0</schemaversion>
        <lomimscc:lom/>
    </metadata>
    <organizations>
        <organization identifier="stuff_O_1" structure="rooted-hierarchy">
            <item identifier="stuff_O_1_1">
                <item identifier="stuff_O_1_000001" identifierref="000001">
                    <title>Online Resource</title>
                </item>
            </item>
        </organization>
    </organizations>
    <resources>
        <resource identifier="000001" type="imsbasiclti_xmlv1p0">
            <file href="000001/BasicLTI.xml"/>
        </resource>
    </resources>
</manifest>
```

**Comment by claydiffrient** [comment] 2015-01-14 15:43
@mradcliffe Thanks for your response.  Using the data you provided and the steps you originally posted, I can't reproduce the issue.  I'm going to close it now, but feel free to reopen it if you have further issues.

**Closed by claydiffrient** 2015-01-14 15:43 UTC
