### ISSUE TITLE
Editing course section name and moving to another page afterwards results in error

### ISSUE THREAD

**Issue by vedranmiletic** [instructure/canvas-lms#347] opened 2013-09-02 12:12 UTC
Hi,

I have no local Canvas installation, so I'm using canvas.instructure.com. If one goes to Settings, then Sections and edits name of a section, and then moves to another page, say Home, webpage gets filled with content containing JavaScript code.

However, if after editing section name one goes to another tab, say Course Details, the error does not occur.

In any case change to section name is saved.

**Comment by rivanvx** [comment] 2015-01-01 19:54
This happens with Firefox on Linux. I can still reproduce it reliably.

**Comment by tierra** [comment] 2016-10-11 13:57
I know this issue is old, but I want to get some old open issues cleaned up, and wanted to simply ping those involved in this for any possible update. It doesn't seem like an issue that was ever run into by anyone else since it was opened, and was never able to be reproduced.

Unless this can be reproduced now, I'm going to close this out in the next couple weeks.

**Closed** 2016-10-26 15:05 UTC
